Movie title;
Movie c2to3;
Movie c3to2;
Movie door2D;
Movie door3D;


Movie win;
Movie toWin;
Gif keyDice;
PFont oswald;
PImage map2ds;
PImage map3ds;

//dimen choose
//PImage choosed;
PImage chooseR;
PImage chooseY;
Gif chooseSpinR;
Gif chooseSpinY;

//PImage red3dBack;
//PImage red3dForward;
//PImage red3dLeft;
//PImage red3dRight;
//PImage red2dDown;
//PImage red2dLeft;
//PImage red2dRight;
//PImage red2dUp;
//PImage blue2dDown;
//PImage blue2dLeft;
//PImage blue2dRight;
//PImage blue2dUp;
//PImage blue3dBack;
//PImage blue3dForward;
//PImage blue3dLeft;
//PImage blue3dRight;
PImage pieceR;
PImage pieceY;
Gif pieceRspin;
Gif pieceYspin;

PImage turnR;
PImage turnB;
PImage keya;
PImage keyb;
PImage dlogo_a2d;
PImage dlogo_a3d;
PImage dlogo_b2d;
PImage dlogo_b3d;
//scenario
PImage scenario12;
PImage scenario13;
PImage bgR;
PImage bgL;
PImage scenario2L2;
PImage scenario2L3;
PImage scenario2R2;
PImage scenario2R3;
Movie scenario1;
Movie scenario2;
Movie S2stairsStop;
Movie S2L2to3;
Movie S2R3to2;
Movie S2wrong;

Movie stop1;
Movie stop2;
Movie dice1;
Movie dice2;
Movie dice3;
Movie dice4;
Movie dice5;
Movie dice6;

void initialInterface() {
  map3ds = loadImage("map3ds.jpg");
  map2ds = loadImage("map2ds.jpg");
  //choosed = loadImage("chooseview.jpg");
  title = new Movie(this, "title.mov");
  scenario1 = new Movie(this, "scenario1.mov");
  scenario2 = new Movie(this, "scenario2.mov");
  S2stairsStop = new Movie(this, "S2stairs.mov");
  S2L2to3 = new Movie(this, "S2L2to3.mov");
  S2R3to2 = new Movie(this, "S2R3to2.mov");
  S2wrong = new Movie(this, "S2wrong.mov");
  c2to3 = new Movie(this, "2to3.mov");
  c3to2 = new Movie(this, "3to2.mov");
  door2D = new Movie(this, "door2d.mov");
  door3D = new Movie(this, "door3d.mov");
  win = new Movie(this, "win.mov");
  chooseR = loadImage("chooseR.jpg");
  chooseY = loadImage("chooseY.jpg");
  chooseSpinR = new Gif(this, "chooseSpinR.gif");
  chooseSpinY = new Gif(this, "chooseSpinY.gif");
//  red3dBack = loadImage("red3dBack.png");
//  red3dForward = loadImage("red3dForward.png");
//  red3dLeft = loadImage("red3dLeft.png");
//  red3dRight = loadImage("red3dRight.png");
//  red2dDown = loadImage("red2dDown.png");
//  red2dLeft = loadImage("red2dLeft.png");
//  red2dRight = loadImage("red2dRight.png");
//  red2dUp = loadImage("red2dUp.png");
//  blue2dDown = loadImage("blue2dDown.png");
//  blue2dLeft = loadImage("blue2dLeft.png");
//  blue2dRight = loadImage("blue2dRight.png"); 
//  blue2dUp = loadImage("blue2dUp.png");
//  blue3dBack = loadImage("blue3dBack.png");
//  blue3dForward = loadImage("blue3dForward.png");
//  blue3dLeft = loadImage("blue3dLeft.png");
//  blue3dRight = loadImage("blue3dRight.png");
  pieceR = loadImage("piecer.png");
  pieceY = loadImage("piecey.png");
  pieceRspin = new Gif(this, "piecer_spin.gif");
  pieceYspin = new Gif(this, "piecey_spin.gif");
  turnR = loadImage("turnR.png");
  turnB = loadImage("turnB.png");
  oswald = loadFont("Oswald-28.vlw");
  stop1 = new Movie(this, "staireffect1.mov");
  stop2 = new Movie(this, "staireffect2.mov");
  toWin = new Movie(this, "howwin1.mov");
  keyDice = new Gif(this, "keySpaceTrow.gif");
  keya = loadImage("keyA.png");
  keyb = loadImage("keyB.png");
  dice1 = new Movie(this, "dice1.mov");
  dice2 = new Movie(this, "dice2.mov");
  dice3 = new Movie(this, "dice3.mov");
  dice4 = new Movie(this, "dice4.mov");
  dice5 = new Movie(this, "dice5.mov");
  dice6 = new Movie(this, "dice6.mov");
  dlogo_a2d = loadImage("dlogo_a2d.png");
  dlogo_a3d = loadImage("dlogo_a3d.png");
  dlogo_b2d = loadImage("dlogo_b2d.png");
  dlogo_b3d = loadImage("dlogo_b3d.png");
  scenario12 = loadImage("senario1.2.jpg");
  scenario13 = loadImage("senario1.3.jpg");
  bgR = loadImage("bgR.jpg");
  bgL = loadImage("bgL.jpg");
  scenario2L2 = loadImage("senario2_L2d.png");
  scenario2L3 = loadImage("senario2_L3d.png");
  scenario2R2 = loadImage("senario2_R2d.png");
  scenario2R3 = loadImage("senario2_R3d.png");
}

