Movie title;
Movie c2to3;
Movie c3to2;
Movie door2D;
Movie door3D;
Movie map2d;
Movie intro1;
Movie win;
Movie toWin;
Gif keyDice;
PFont oswald;
PImage map3d;
PImage choosed;
PImage red3dBack;
PImage red3dForward;
PImage red3dLeft;
PImage red3dRight;
PImage red2dDown;
PImage red2dLeft;
PImage red2dRight;
PImage red2dUp;
PImage blue2dDown;
PImage blue2dLeft;
PImage blue2dRight;
PImage blue2dUp;
PImage blue3dBack;
PImage blue3dForward;
PImage blue3dLeft;
PImage blue3dRight;
PImage turnR;
PImage turnB;
Gif keya;
Gif keyb;
Movie stop1;
Movie stop2;
Movie dice1;
Movie dice2;
Movie dice3;
Movie dice4;
Movie dice5;
Movie dice6;

void initialInterface() {
  map3d = loadImage("introduction level_map-02.png");
  map2d = new Movie(this, "bg.mov");
  choosed = loadImage("chooseview.jpg");
  title = new Movie(this, "title.mov");
  intro1 = new Movie(this, "intro_23d.mov");
  c2to3 = new Movie(this, "2to3.mov");
  c3to2 = new Movie(this, "3to2.mov");
  door2D = new Movie(this, "door2d.mov");
  door3D = new Movie(this, "door3d.mov");
  win = new Movie(this, "win.mov");
  red3dBack = loadImage("red3dBack.png");
  red3dForward = loadImage("red3dForward.png");
  red3dLeft = loadImage("red3dLeft.png");
  red3dRight = loadImage("red3dRight.png");
  red2dDown = loadImage("red2dDown.png");
  red2dLeft = loadImage("red2dLeft.png");
  red2dRight = loadImage("red2dRight.png");
  red2dUp = loadImage("red2dUp.png");
  blue2dDown = loadImage("blue2dDown.png");
  blue2dLeft = loadImage("blue2dLeft.png");
  blue2dRight = loadImage("blue2dRight.png"); 
  blue2dUp = loadImage("blue2dUp.png");
  blue3dBack = loadImage("blue3dBack.png");
  blue3dForward = loadImage("blue3dForward.png");
  blue3dLeft = loadImage("blue3dLeft.png");
  blue3dRight = loadImage("blue3dRight.png");
  turnR = loadImage("turnR.png");
  turnB = loadImage("turnB.png");
  oswald = loadFont("Oswald-28.vlw");
  stop1 = new Movie(this, "staireffect1.mov");
  stop2 = new Movie(this, "staireffect2.mov");
  toWin = new Movie(this, "howwin1.mov");
  keyDice = new Gif(this, "keySpaceTrow.gif");
  keya = new Gif(this, "keya.gif");
  keyb = new Gif(this, "keyb.gif");
  dice1 = new Movie(this, "dice1.mov");
  dice2 = new Movie(this, "dice2.mov");
  dice3 = new Movie(this, "dice3.mov");
  dice4 = new Movie(this, "dice4.mov");
  dice5 = new Movie(this, "dice5.mov");
  dice6 = new Movie(this, "dice6.mov");
}

